"""empty message

Revision ID: 1f4c08ab3026
Revises: 234ecb826619
Create Date: 2016-11-25 16:07:51.756359

"""

# revision identifiers, used by Alembic.
revision = '1f4c08ab3026'
down_revision = '234ecb826619'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tupians', sa.Column('geshi', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tupians', 'geshi')
    ### end Alembic commands ###
