"""empty message

Revision ID: 42748c120f6e
Revises: 9826835de990
Create Date: 2016-11-14 11:08:56.381891

"""

# revision identifiers, used by Alembic.
revision = '42748c120f6e'
down_revision = '9826835de990'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fengmians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fmpath', sa.String(length=128), nullable=True),
    sa.Column('xiangce_id', sa.Integer(), nullable=True),
    sa.Column('tupian_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tupian_id'], ['tupians.id'], ),
    sa.ForeignKeyConstraint(['xiangce_id'], ['xiangces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fmpath')
    )
    op.drop_table('feng_mian')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feng_mian',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('fmpath', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('xiangce_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tupian_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tupian_id'], ['tupians.id'], name='feng_mian_ibfk_1'),
    sa.ForeignKeyConstraint(['xiangce_id'], ['xiangces.id'], name='feng_mian_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('fengmians')
    ### end Alembic commands ###
