"""empty message

Revision ID: 5b850df024de
Revises: None
Create Date: 2016-10-02 15:07:16.310112

"""

# revision identifiers, used by Alembic.
revision = '5b850df024de'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xiangces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xcname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xcname')
    )
    op.create_table('tupians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tppath', sa.String(length=300), nullable=True),
    sa.Column('xiangce_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['xiangce_id'], ['xiangces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tppath')
    )
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_table('tupians')
    op.drop_table('xiangces')
    ### end Alembic commands ###
