"""empty message

Revision ID: 886862081ebe
Revises: c46672c7bcf1
Create Date: 2016-11-03 14:04:11.452182

"""

# revision identifiers, used by Alembic.
revision = '886862081ebe'
down_revision = 'c46672c7bcf1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tupians', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('tupians', 'member_since')
    op.add_column('xiangces', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.drop_column('xiangces', 'menber_since')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xiangces', sa.Column('menber_since', mysql.DATETIME(), nullable=True))
    op.drop_column('xiangces', 'member_since')
    op.add_column('tupians', sa.Column('member_since', mysql.DATETIME(), nullable=True))
    op.drop_column('tupians', 'timestamp')
    ### end Alembic commands ###
