"""empty message

Revision ID: 9826835de990
Revises: 886862081ebe
Create Date: 2016-11-14 11:07:12.780148

"""

# revision identifiers, used by Alembic.
revision = '9826835de990'
down_revision = '886862081ebe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feng_mian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fmpath', sa.String(length=128), nullable=True),
    sa.Column('xiangce_id', sa.Integer(), nullable=True),
    sa.Column('tupian_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tupian_id'], ['tupians.id'], ),
    sa.ForeignKeyConstraint(['xiangce_id'], ['xiangces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fmpath')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feng_mian')
    ### end Alembic commands ###
