"""empty message

Revision ID: baf011d2ab77
Revises: 40418ac40fdd
Create Date: 2016-12-15 16:23:58.646020

"""

# revision identifiers, used by Alembic.
revision = 'baf011d2ab77'
down_revision = '40418ac40fdd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    ### end Alembic commands ###
