"""empty message

Revision ID: c46672c7bcf1
Revises: 5b850df024de
Create Date: 2016-11-03 11:53:47.579561

"""

# revision identifiers, used by Alembic.
revision = 'c46672c7bcf1'
down_revision = '5b850df024de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tupians', sa.Column('about_tp', sa.Text(), nullable=True))
    op.add_column('tupians', sa.Column('last_since', sa.DateTime(), nullable=True))
    op.add_column('tupians', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('tupians', sa.Column('tpname', sa.String(length=64), nullable=True))
    op.add_column('xiangces', sa.Column('about_xc', sa.Text(), nullable=True))
    op.add_column('xiangces', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('xiangces', sa.Column('menber_since', sa.DateTime(), nullable=True))
    op.add_column('xiangces', sa.Column('tpshu', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xiangces', 'tpshu')
    op.drop_column('xiangces', 'menber_since')
    op.drop_column('xiangces', 'last_seen')
    op.drop_column('xiangces', 'about_xc')
    op.drop_column('tupians', 'tpname')
    op.drop_column('tupians', 'member_since')
    op.drop_column('tupians', 'last_since')
    op.drop_column('tupians', 'about_tp')
    ### end Alembic commands ###
