"""empty message

Revision ID: c9f6bc1971d2
Revises: 42748c120f6e
Create Date: 2016-11-16 17:42:32.690899

"""

# revision identifiers, used by Alembic.
revision = 'c9f6bc1971d2'
down_revision = '42748c120f6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fengmians', sa.Column('lspath', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'fengmians', ['lspath'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fengmians', type_='unique')
    op.drop_column('fengmians', 'lspath')
    ### end Alembic commands ###
