"""empty message

Revision ID: e29d34e31d80
Revises: 1f4c08ab3026
Create Date: 2016-11-25 16:51:30.064051

"""

# revision identifiers, used by Alembic.
revision = 'e29d34e31d80'
down_revision = '1f4c08ab3026'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fm', table_name='tupians')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('fm', 'tupians', ['fm'], unique=True)
    ### end Alembic commands ###
